name: ccai9012
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blas=1.0
  - boost-cpp=1.82.0
  - branca=0.6.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cairo=1.16.0
  - certifi=2025.6.15
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - contourpy=1.3.2
  - cycler=0.12.1
  - expat=2.7.1
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.4
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - geographiclib=2.0
  - geopy=2.4.1
  - gettext=0.21.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - graphviz=12.2.1
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=73.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libboost=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcurl=8.12.1
  - libcxx=20.1.7
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libhwloc=2.11.2
  - libiconv=1.18
  - libltdl=2.4.3a
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - librsvg=2.56.3
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libtool=2.5.4
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - llvm-openmp=17.0.6
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.1
  - munkres=1.1.4
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89.1
  - numba=0.61.0
  - numpy-base=2.1.3
  - openjpeg=2.5.2
  - openssl=3.5.0
  - pandas=2.3.0
  - pango=1.50.7
  - patsy=1.0.1
  - pcre2=10.42
  - pip=25.1
  - pixman=0.40.0
  - poppler=24.09.0
  - poppler-data=0.4.12
  - pygraphviz=1.14
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.13.4
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.2
  - scipy=1.15.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=72.1.0
  - shap=0.48.0
  - six=1.17.0
  - slicer=0.0.8
  - sqlite=3.45.3
  - statsmodels=0.14.4
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tqdm=4.67.1
  - typing_extensions=4.14.0
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.7.0
      - aif360==0.6.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - audioop-lts==0.2.1
      - av==13.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blis==1.3.0
      - catalogue==2.0.10
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - choreographer==1.0.9
      - click==8.2.1
      - cloudpathlib==0.22.0
      - cloup==3.0.7
      - comm==0.2.2
      - confection==0.1.5
      - cymem==2.0.11
      - cython==3.1.2
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diffusers==0.33.1
      - dill==0.3.8
      - distro==1.9.0
      - executing==2.2.0
      - faiss-cpu==1.11.0.post1
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - geopandas==1.1.0
      - glcontext==3.0.0
      - h11==0.16.0
      - hf-xet==1.1.3
      - hiddenlayer==0.3
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.32.4
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - ipykernel==6.29.5
      - ipython==9.3.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - isosurfaces==0.1.2
      - jedi==0.19.2
      - jiter==0.10.0
      - json5==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - jupytext==1.17.2
      - kaleido==1.0.0
      - kiwisolver==1.4.8
      - langchain==0.3.27
      - langchain-community==0.3.27
      - langchain-core==0.3.72
      - langchain-deepseek==0.1.4
      - langchain-huggingface==0.2.0
      - langchain-openai==0.3.28
      - langchain-text-splitters==0.3.9
      - langcodes==3.5.0
      - langsmith==0.3.45
      - language-data==1.3.0
      - lap==0.5.12
      - lightgbm==4.6.0
      - logistro==1.1.0
      - mako==1.3.10
      - manim==0.19.0
      - manimpango==0.6.0
      - mapbox-earcut==1.0.3
      - marisa-trie==1.3.1
      - markdown==3.9
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mistune==3.1.3
      - moderngl==5.12.0
      - moderngl-window==3.1.1
      - moviepy==2.2.1
      - mpmath==1.3.0
      - multidict==6.5.0
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - mypy-extensions==1.1.0
      - narwhals==2.0.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - notebook==7.4.3
      - notebook-shim==0.2.4
      - numpy==2.3.0
      - openai==1.97.1
      - opencv-python==4.11.0.86
      - opentsne==1.0.2
      - orjson==3.10.18
      - osmnx==2.0.6
      - overrides==7.7.0
      - packaging==24.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pdoc3==0.11.6
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - plotly==6.2.0
      - preshed==3.0.10
      - proglog==0.1.12
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pycairo==1.28.0
      - pycparser==2.22
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pydub==0.25.1
      - pyglet==2.1.6
      - pyglm==2.8.2
      - pygments==2.19.1
      - pyobjc-core==11.1
      - pyobjc-framework-cocoa==11.1
      - pyogrio==0.11.0
      - pypdf==5.9.0
      - pyproj==3.7.1
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - qwen-vl-utils==0.0.11
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - screeninfo==0.8.1
      - send2trash==1.8.3
      - sentence-transformers==4.1.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - simplejson==3.20.1
      - skia-pathops==0.8.0.post2
      - smart-open==7.3.1
      - sniffio==1.3.1
      - soupsieve==2.7
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.41
      - srsly==2.5.1
      - srt==3.5.3
      - stack-data==0.6.3
      - svgelements==1.9.6
      - sympy==1.14.0
      - tenacity==9.1.2
      - terminado==0.18.1
      - thinc==8.3.6
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - torch==2.7.1
      - torchsummary==1.5.1
      - torchvision==0.22.1
      - tornado==6.5.1
      - traitlets==5.14.3
      - transformers==4.52.4
      - typer==0.19.1
      - types-python-dateutil==2.9.0.20250516
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - ultralytics==8.3.159
      - ultralytics-thop==2.0.14
      - uri-template==1.3.0
      - urllib3==2.4.0
      - wasabi==1.1.3
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - wordcloud==1.9.4
      - wrapt==1.17.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
      - zstandard==0.23.0
